import { Icon, Navbar } from '@miroiu/components';
import type { Metadata } from 'next';
import { Providers } from './providers';

import NextLink from 'next/link';
import { Link } from '@nextui-org/link';

import './globals.css';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body>
				<Providers>
					<Navbar className="max-w-3xl mx-auto px-6" />
					<main
						id="skip"
						className="scroll-m-5 max-w-3xl mx-auto px-6 my-6"
					>
						{children}
					</main>
					<footer className="mt-16 mb-8 max-w-3xl mx-auto px-6">
						<div className="flex items-center gap-4 mb-6">
							<h3 className="text-xl font-semibold">
								Reached the end
							</h3>
							<Icon name="check" className="h-8 text-highlight" />
						</div>
						<div className="relative grid grid-cols-2 sm:grid-cols-3 overflow-hidden">
							<div className="flex flex-col gap-3">
								<Link
									as={NextLink}
									href="/"
									className="text-secondary"
								>
									Home
								</Link>
								<Link
									as={NextLink}
									href="/snippets"
									className="text-secondary"
								>
									Snippets
								</Link>
								<Link
									as={NextLink}
									href="/blog"
									className="text-secondary"
								>
									Blog
								</Link>
							</div>
							<div className="flex flex-col gap-3">
								<Link
									isExternal
									as={NextLink}
									href="https://www.linkedin.com/in/miroiu-gabriel"
									className="text-secondary"
								>
									<Icon
										name="linkedIn"
										className="w-6 h-6 mr-2"
									/>
									LinkedIn
								</Link>
								<Link
									as={NextLink}
									href="https://github.com/MiroiuGabriel"
									className="text-secondary"
								>
									<Icon
										name="github"
										className="w-6 h-6 mr-2"
									/>
									Github
								</Link>
								<Link
									as={NextLink}
									href="/resume.pdf"
									isExternal
									className="text-secondary"
								>
									Resume
								</Link>
							</div>
							<div className="hidden sm:flex flex-col items-center justify-center">
								<Link as={NextLink} href="/">
									<Icon
										name="brandOutline"
										className="w-24 h-24"
									/>
								</Link>
							</div>
						</div>
					</footer>
				</Providers>
			</body>
		</html>
	);
}
